# server/Dockerfile-dev

# Install node image in container
FROM node

# Install nodemon for hot reloading
RUN npm install -g nodemon

# Create and set the working directory
RUN mkdir -p /app/server
WORKDIR /app/server/

# Copy the dependency files over
COPY package*.json /app/server/

# Install dependencies
RUN npm install
RUN npm install express
RUN npm install twitter

# Copy the server files over
COPY . /app/server/

# Command to run the server files
CMD ["nodemon","server.js"]